### ISSUE TITLE
superfluous parameter

### ISSUE THREAD

**Issue by leviwheatcroft** [XeroAPI/xero-node-sample-app#3]
Really helpful sample app... 

I don't mean to be a pedant, but noticed a minor error [here](https://github.com/XeroAPI/xero-node-sample-app/blob/master/index.js#L136)

the fn declaration for `getXeroClient` is `function getXeroClient(session)`

so `returnTo` in `var xeroClient = getXeroClient(req.session, returnTo);` on line 136 is redundant.

**Comment by SidneyAllen** [comment]
This code base is deprecated as it's for OAuth 1.0a.  

Please see the [OAuth 2.0 kitchen sync app](https://github.com/XeroAPI/xero-node-oauth2-app) for use with xero-node 4.x

OAuth1.0a deprecation schedule
* Early December 2019 - No new OAuth 1.0a apps created.
* Mid December 2019 - OAuth 2.0 migration endpoint available to partner apps.
* December 2020 - OAuth 1.0a no longer supported for existing integrations.
