### ISSUE TITLE
Unable to find the Reports API in this sample - but it works on the demo

### ISSUE THREAD

**Issue by onlinelaser** [XeroAPI/xero-node-sample-app#6]
I'm trying to work out how to use the xero-node BankStatement report by examining this sample app.

The live Heroku demo is pulling back all the Reports API endpoints correctly but unless I'm missing something the sample app in this repo doesn't appear to have the reports code in it??

Is the demo out of sync with this repo perhaps?

**Comment by SidneyAllen** [comment]
This code base is deprecated as it's for OAuth 1.0a.  

Please see the [OAuth 2.0 kitchen sync app](https://github.com/XeroAPI/xero-node-oauth2-app) for use with xero-node 4.x

OAuth1.0a deprecation schedule
* Early December 2019 - No new OAuth 1.0a apps created.
* Mid December 2019 - OAuth 2.0 migration endpoint available to partner apps.
* December 2020 - OAuth 1.0a no longer supported for existing integrations.
